resources:
- deployment.yaml
- secrets.yaml
- ingress.yaml
- service.yaml
- namespace.yaml
namespace: om-webserver-xihe
commonLabels:
  common-app: om-webserver
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/om/om-webserver
  newName: swr.cn-north-4.myhuaweicloud.com/om/om-webserver-prod
  newTag: xihe-icsl-cf0ef2
